In [1]:
import pandas as pd
import pandas as pd
import numpy as np




In [2]:
data = pd.read_csv('cleaned_data.csv')
data.head()

Age  Number of sexual partners  First sexual intercourse  \
0   18                          6                         5   
1   15                          0                         4   
2   34                          0                         5   
3   52                          7                         6   
4   46                          5                        11   

   Num of pregnancies  Smokes  Smokes (years)  Smokes (packs/year)  \
0                   1       0               0                    0   
1                   1       0               0                    0   
2                   1       0               0                    0   
3                   6       1              23                   49   
4                   6       0               0                    0   

   Hormonal Contraceptives  Hormonal Contraceptives (years)  IUD  ...  \
0                        0                                0    0  ...   
1                        0                                0    0  ...   
2                        0                                0    0  ...   
3                        1                               29    0  ...   
4                        1                               20    0  ...   

   STDs: Time since first diagnosis  STDs: Time since last diagnosis  \
0                                 0                                0   
1                                 0                                0   
2                                 0                                0   
3                                 0                                0   
4                                 0                                0   

   Dx:Cancer  Dx:CIN  Dx:HPV  Dx  Hinselmann  Schiller  Citology  Biopsy  
0          0       0       0   0           0         0         0       0  
1          0       0       0   0           0         0         0       0  
2          0       0       0   0           0         0         0       0  
3          1       0       1   0           0         0         0       0  
4          0       0       0   0           0         0         0       0  

[5 rows x 36 columns]

In [3]:
X=data.drop(['Biopsy'], axis=1)
y=data['Biopsy']

Over Sampling



In [4]:
from sklearn.model_selection import StratifiedKFold
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score
from imblearn.over_sampling import SMOTE, ADASYN, RandomOverSampler
import numpy as np

# Number of folds
n_splits = 10

# Initialize StratifiedKFold
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)

# Initialize lists to store metrics for each fold
accuracy_list = []
precision_list = []
recall_list = []
f1_list = []
uncertainty_list = []  # List to store entropy for each fold
confusion_matrices = []

# Choose an oversampling method
oversampler = SMOTE(random_state=42)
# oversampler = ADASYN(random_state=42)
#oversampler = RandomOverSampler(random_state=42)

# Function to calculate entropy
def calculate_entropy(probabilities):
    entropy = -np.sum(probabilities * np.log(probabilities + 1e-9), axis=1)  # Add small value to avoid log(0)
    return np.mean(entropy)

# Loop through the StratifiedKFold splits
for train_index, test_index in skf.split(X, y):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    
    # Apply oversampling
    X_train_resampled, y_train_resampled = oversampler.fit_resample(X_train, y_train)
    
    # Initialize and train the SVM model with probability enabled
    svm_model = SVC(probability=True, random_state=42)
    svm_model.fit(X_train_resampled, y_train_resampled)
    
    # Predict probabilities and classes
    y_pred_svm = svm_model.predict(X_test)
    y_prob_svm = svm_model.predict_proba(X_test)
    
    # Calculate and store entropy
    entropy = calculate_entropy(y_prob_svm)
    uncertainty_list.append(entropy)
    
    # Store metrics
    accuracy_list.append(accuracy_score(y_test, y_pred_svm))
    precision_list.append(precision_score(y_test, y_pred_svm))
    recall_list.append(recall_score(y_test, y_pred_svm))
    f1_list.append(f1_score(y_test, y_pred_svm))
    
    # Store confusion matrix
    conf_matrix = confusion_matrix(y_test, y_pred_svm)
    confusion_matrices.append(conf_matrix)
    print(f'Confusion Matrix for Fold {len(confusion_matrices)}:\n', conf_matrix)

# Calculate mean and standard deviation of each metric
mean_accuracy = np.mean(accuracy_list)
std_accuracy = np.std(accuracy_list)
mean_precision = np.mean(precision_list)
std_precision = np.std(precision_list)
mean_recall = np.mean(recall_list)
std_recall = np.std(recall_list)
mean_f1 = np.mean(f1_list)
std_f1 = np.std(f1_list)

# Calculate mean and standard deviation of entropy
mean_entropy = np.mean(uncertainty_list)
std_entropy = np.std(uncertainty_list)

# Calculate mean confusion matrix
mean_conf_matrix = np.mean(confusion_matrices, axis=0)

# Print results
print('Mean Accuracy:', mean_accuracy)
print('Accuracy Std Dev:', std_accuracy)
print('Mean Precision:', mean_precision)
print('Precision Std Dev:', std_precision)
print('Mean Recall:', mean_recall)
print('Recall Std Dev:', std_recall)
print('Mean F1-score:', mean_f1)
print('F1-score Std Dev:', std_f1)
print('Mean Entropy:', mean_entropy)
print('Entropy Std Dev:', std_entropy)
print('Mean Confusion Matrix:\n', mean_conf_matrix)


Confusion Matrix for Fold 1:
 [[66 15]
 [ 4  1]]
Confusion Matrix for Fold 2:
 [[67 14]
 [ 4  1]]
Confusion Matrix for Fold 3:
 [[60 21]
 [ 3  2]]
Confusion Matrix for Fold 4:
 [[70 10]
 [ 4  2]]
Confusion Matrix for Fold 5:
 [[64 16]
 [ 1  5]]
Confusion Matrix for Fold 6:
 [[65 15]
 [ 5  1]]
Confusion Matrix for Fold 7:
 [[56 24]
 [ 3  3]]
Confusion Matrix for Fold 8:
 [[62 18]
 [ 3  3]]
Confusion Matrix for Fold 9:
 [[65 15]
 [ 3  2]]
Confusion Matrix for Fold 10:
 [[65 15]
 [ 1  4]]
Mean Accuracy: 0.773953488372093
Accuracy Std Dev: 0.04202025954880806
Mean Precision: 0.1265526721748959
Precision Std Dev: 0.05919942172024951
Mean Recall: 0.4333333333333333
Recall Std Dev: 0.22261077142752
Mean F1-score: 0.19407888407888407
F1-score Std Dev: 0.0917841191842333
Mean Entropy: 0.510744657641474
Entropy Std Dev: 0.02766867542750917
Mean Confusion Matrix:
 [[64.  16.3]
 [ 3.1  2.4]]


In [5]:
from sklearn.model_selection import StratifiedKFold
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score
from imblearn.under_sampling import NearMiss, ClusterCentroids, TomekLinks, RandomUnderSampler
import numpy as np

# Define entropy function
def calculate_entropy(probabilities):
    epsilon = 1e-10  # Small constant to avoid log(0)
    return -np.mean(np.sum(probabilities * np.log(probabilities + epsilon), axis=1))

# Number of folds
n_splits = 10

# Initialize StratifiedKFold
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)

# Initialize lists to store metrics for each fold
accuracy_list_before = []
precision_list_before = []
recall_list_before = []
f1_list_before = []
entropy_list_before = []
confusion_matrices_before = []

accuracy_list_nearmiss = []
precision_list_nearmiss = []
recall_list_nearmiss = []
f1_list_nearmiss = []
entropy_list_nearmiss = []
confusion_matrices_nearmiss = []

accuracy_list_clustercentroids = []
precision_list_clustercentroids = []
recall_list_clustercentroids = []
f1_list_clustercentroids = []
entropy_list_clustercentroids = []
confusion_matrices_clustercentroids = []

accuracy_list_tomeklinks = []
precision_list_tomeklinks = []
recall_list_tomeklinks = []
f1_list_tomeklinks = []
entropy_list_tomeklinks = []
confusion_matrices_tomeklinks = []

accuracy_list_random = []
precision_list_random = []
recall_list_random = []
f1_list_random = []
entropy_list_random = []
confusion_matrices_random = []

# Loop through the StratifiedKFold splits
for train_index, test_index in skf.split(X, y):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    
    # Initialize and train the SVM model without undersampling
    svm_model = SVC(probability=True, random_state=42)
    svm_model.fit(X_train, y_train)
    
    # Predictions and probabilities before undersampling
    y_pred_before = svm_model.predict(X_test)
    y_prob_before = svm_model.predict_proba(X_test)
    
    # Calculate entropy before undersampling
    entropy_before = calculate_entropy(y_prob_before)
    entropy_list_before.append(entropy_before)
    
    # Store metrics before undersampling
    accuracy_list_before.append(accuracy_score(y_test, y_pred_before))
    precision_list_before.append(precision_score(y_test, y_pred_before))
    recall_list_before.append(recall_score(y_test, y_pred_before))
    f1_list_before.append(f1_score(y_test, y_pred_before))
    confusion_matrices_before.append(confusion_matrix(y_test, y_pred_before))
    
    # Apply NearMiss to the training data
    nearmiss = NearMiss(version=1)
    X_train_nearmiss, y_train_nearmiss = nearmiss.fit_resample(X_train, y_train)
    
    # Initialize and train the SVM model with NearMiss
    svm_model_nearmiss = SVC(probability=True, random_state=42)
    svm_model_nearmiss.fit(X_train_nearmiss, y_train_nearmiss)
    
    # Predictions and probabilities after NearMiss
    y_pred_nearmiss = svm_model_nearmiss.predict(X_test)
    y_prob_nearmiss = svm_model_nearmiss.predict_proba(X_test)
    
    # Calculate entropy after NearMiss
    entropy_nearmiss = calculate_entropy(y_prob_nearmiss)
    entropy_list_nearmiss.append(entropy_nearmiss)
    
    # Store metrics after NearMiss
    accuracy_list_nearmiss.append(accuracy_score(y_test, y_pred_nearmiss))
    precision_list_nearmiss.append(precision_score(y_test, y_pred_nearmiss))
    recall_list_nearmiss.append(recall_score(y_test, y_pred_nearmiss))
    f1_list_nearmiss.append(f1_score(y_test, y_pred_nearmiss))
    confusion_matrices_nearmiss.append(confusion_matrix(y_test, y_pred_nearmiss))
    
    # Apply ClusterCentroids to the training data
    clustercentroids = ClusterCentroids(random_state=42)
    X_train_clustercentroids, y_train_clustercentroids = clustercentroids.fit_resample(X_train, y_train)
    
    # Initialize and train the SVM model with ClusterCentroids
    svm_model_clustercentroids = SVC(probability=True, random_state=42)
    svm_model_clustercentroids.fit(X_train_clustercentroids, y_train_clustercentroids)
    
    # Predictions and probabilities after ClusterCentroids
    y_pred_clustercentroids = svm_model_clustercentroids.predict(X_test)
    y_prob_clustercentroids = svm_model_clustercentroids.predict_proba(X_test)
    
    # Calculate entropy after ClusterCentroids
    entropy_clustercentroids = calculate_entropy(y_prob_clustercentroids)
    entropy_list_clustercentroids.append(entropy_clustercentroids)
    
    # Store metrics after ClusterCentroids
    accuracy_list_clustercentroids.append(accuracy_score(y_test, y_pred_clustercentroids))
    precision_list_clustercentroids.append(precision_score(y_test, y_pred_clustercentroids))
    recall_list_clustercentroids.append(recall_score(y_test, y_pred_clustercentroids))
    f1_list_clustercentroids.append(f1_score(y_test, y_pred_clustercentroids))
    confusion_matrices_clustercentroids.append(confusion_matrix(y_test, y_pred_clustercentroids))
    
    # Apply TomekLinks to the training data
    tomeklinks = TomekLinks()
    X_train_tomeklinks, y_train_tomeklinks = tomeklinks.fit_resample(X_train, y_train)
    
    # Initialize and train the SVM model with TomekLinks
    svm_model_tomeklinks = SVC(probability=True, random_state=42)
    svm_model_tomeklinks.fit(X_train_tomeklinks, y_train_tomeklinks)
    
    # Predictions and probabilities after TomekLinks
    y_pred_tomeklinks = svm_model_tomeklinks.predict(X_test)
    y_prob_tomeklinks = svm_model_tomeklinks.predict_proba(X_test)
    
    # Calculate entropy after TomekLinks
    entropy_tomeklinks = calculate_entropy(y_prob_tomeklinks)
    entropy_list_tomeklinks.append(entropy_tomeklinks)
    
    # Store metrics after TomekLinks
    accuracy_list_tomeklinks.append(accuracy_score(y_test, y_pred_tomeklinks))
    precision_list_tomeklinks.append(precision_score(y_test, y_pred_tomeklinks))
    recall_list_tomeklinks.append(recall_score(y_test, y_pred_tomeklinks))
    f1_list_tomeklinks.append(f1_score(y_test, y_pred_tomeklinks))
    confusion_matrices_tomeklinks.append(confusion_matrix(y_test, y_pred_tomeklinks))
    
    # Apply RandomUnderSampler to the training data
    random_undersampler = RandomUnderSampler(random_state=42)
    X_train_random, y_train_random = random_undersampler.fit_resample(X_train, y_train)
    
    # Initialize and train the SVM model with RandomUnderSampler
    svm_model_random = SVC(probability=True, random_state=42)
    svm_model_random.fit(X_train_random, y_train_random)
    
    # Predictions and probabilities after RandomUnderSampler
    y_pred_random = svm_model_random.predict(X_test)
    y_prob_random = svm_model_random.predict_proba(X_test)
    
    # Calculate entropy after RandomUnderSampler
    entropy_random = calculate_entropy(y_prob_random)
    entropy_list_random.append(entropy_random)
    
    # Store metrics after RandomUnderSampler
    accuracy_list_random.append(accuracy_score(y_test, y_pred_random))
    precision_list_random.append(precision_score(y_test, y_pred_random))
    recall_list_random.append(recall_score(y_test, y_pred_random))
    f1_list_random.append(f1_score(y_test, y_pred_random))
    confusion_matrices_random.append(confusion_matrix(y_test, y_pred_random))
    
    # Print confusion matrices for each method
    print(f'Confusion Matrix for Fold {len(confusion_matrices_before)} Before Undersampling:\n', confusion_matrices_before[-1])
    print(f'Confusion Matrix for Fold {len(confusion_matrices_nearmiss)} After NearMiss:\n', confusion_matrices_nearmiss[-1])
    print(f'Confusion Matrix for Fold {len(confusion_matrices_clustercentroids)} After ClusterCentroids:\n', confusion_matrices_clustercentroids[-1])
    print(f'Confusion Matrix for Fold {len(confusion_matrices_tomeklinks)} After TomekLinks:\n', confusion_matrices_tomeklinks[-1])
    print(f'Confusion Matrix for Fold {len(confusion_matrices_random)} After RandomUnderSampler:\n', confusion_matrices_random[-1])

# Calculate mean and standard deviation of each metric before undersampling
mean_accuracy_before = np.mean(accuracy_list_before)
std_accuracy_before = np.std(accuracy_list_before)
mean_precision_before = np.mean(precision_list_before)
std_precision_before = np.std(precision_list_before)
mean_recall_before = np.mean(recall_list_before)
std_recall_before = np.std(recall_list_before)
mean_f1_before = np.mean(f1_list_before)
std_f1_before = np.std(f1_list_before)
mean_entropy_before = np.mean(entropy_list_before)
std_entropy_before = np.std(entropy_list_before)

# Calculate mean and standard deviation of each metric after NearMiss
mean_accuracy_nearmiss = np.mean(accuracy_list_nearmiss)
std_accuracy_nearmiss = np.std(accuracy_list_nearmiss)
mean_precision_nearmiss = np.mean(precision_list_nearmiss)
std_precision_nearmiss = np.std(precision_list_nearmiss)
mean_recall_nearmiss = np.mean(recall_list_nearmiss)
std_recall_nearmiss = np.std(recall_list_nearmiss)
mean_f1_nearmiss = np.mean(f1_list_nearmiss)
std_f1_nearmiss = np.std(f1_list_nearmiss)
mean_entropy_nearmiss = np.mean(entropy_list_nearmiss)
std_entropy_nearmiss = np.std(entropy_list_nearmiss)

# Calculate mean and standard deviation of each metric after ClusterCentroids
mean_accuracy_clustercentroids = np.mean(accuracy_list_clustercentroids)
std_accuracy_clustercentroids = np.std(accuracy_list_clustercentroids)
mean_precision_clustercentroids = np.mean(precision_list_clustercentroids)
std_precision_clustercentroids = np.std(precision_list_clustercentroids)
mean_recall_clustercentroids = np.mean(recall_list_clustercentroids)
std_recall_clustercentroids = np.std(recall_list_clustercentroids)
mean_f1_clustercentroids = np.mean(f1_list_clustercentroids)
std_f1_clustercentroids = np.std(f1_list_clustercentroids)
mean_entropy_clustercentroids = np.mean(entropy_list_clustercentroids)
std_entropy_clustercentroids = np.std(entropy_list_clustercentroids)

# Calculate mean and standard deviation of each metric after TomekLinks
mean_accuracy_tomeklinks = np.mean(accuracy_list_tomeklinks)
std_accuracy_tomeklinks = np.std(accuracy_list_tomeklinks)
mean_precision_tomeklinks = np.mean(precision_list_tomeklinks)
std_precision_tomeklinks = np.std(precision_list_tomeklinks)
mean_recall_tomeklinks = np.mean(recall_list_tomeklinks)
std_recall_tomeklinks = np.std(recall_list_tomeklinks)
mean_f1_tomeklinks = np.mean(f1_list_tomeklinks)
std_f1_tomeklinks = np.std(f1_list_tomeklinks)
mean_entropy_tomeklinks = np.mean(entropy_list_tomeklinks)
std_entropy_tomeklinks = np.std(entropy_list_tomeklinks)

# Calculate mean and standard deviation of each metric after RandomUnderSampler
mean_accuracy_random = np.mean(accuracy_list_random)
std_accuracy_random = np.std(accuracy_list_random)
mean_precision_random = np.mean(precision_list_random)
std_precision_random = np.std(precision_list_random)
mean_recall_random = np.mean(recall_list_random)
std_recall_random = np.std(recall_list_random)
mean_f1_random = np.mean(f1_list_random)
std_f1_random = np.std(f1_list_random)
mean_entropy_random = np.mean(entropy_list_random)
std_entropy_random = np.std(entropy_list_random)

# Calculate mean confusion matrix before and after each method
mean_conf_matrix_before = np.mean(confusion_matrices_before, axis=0)
mean_conf_matrix_nearmiss = np.mean(confusion_matrices_nearmiss, axis=0)
mean_conf_matrix_clustercentroids = np.mean(confusion_matrices_clustercentroids, axis=0)
mean_conf_matrix_tomeklinks = np.mean(confusion_matrices_tomeklinks, axis=0)
mean_conf_matrix_random = np.mean(confusion_matrices_random, axis=0)

# Print results before undersampling
print('--- Before Undersampling ---')
print('Mean Accuracy:', mean_accuracy_before)
print('Accuracy Std Dev:', std_accuracy_before)
print('Mean Precision:', mean_precision_before)
print('Precision Std Dev:', std_precision_before)
print('Mean Recall:', mean_recall_before)
print('Recall Std Dev:', std_recall_before)
print('Mean F1-score:', mean_f1_before)
print('F1-score Std Dev:', std_f1_before)
print('Mean Entropy:', mean_entropy_before)
print('Entropy Std Dev:', std_entropy_before)
print('Mean Confusion Matrix:\n', mean_conf_matrix_before)

# Print results after NearMiss
print('--- After NearMiss ---')
print('Mean Accuracy:', mean_accuracy_nearmiss)
print('Accuracy Std Dev:', std_accuracy_nearmiss)
print('Mean Precision:', mean_precision_nearmiss)
print('Precision Std Dev:', std_precision_nearmiss)
print('Mean Recall:', mean_recall_nearmiss)
print('Recall Std Dev:', std_recall_nearmiss)
print('Mean F1-score:', mean_f1_nearmiss)
print('F1-score Std Dev:', std_f1_nearmiss)
print('Mean Entropy:', mean_entropy_nearmiss)
print('Entropy Std Dev:', std_entropy_nearmiss)
print('Mean Confusion Matrix:\n', mean_conf_matrix_nearmiss)

# Print results after ClusterCentroids
print('--- After ClusterCentroids ---')
print('Mean Accuracy:', mean_accuracy_clustercentroids)
print('Accuracy Std Dev:', std_accuracy_clustercentroids)
print('Mean Precision:', mean_precision_clustercentroids)
print('Precision Std Dev:', std_precision_clustercentroids)
print('Mean Recall:', mean_recall_clustercentroids)
print('Recall Std Dev:', std_recall_clustercentroids)
print('Mean F1-score:', mean_f1_clustercentroids)
print('F1-score Std Dev:', std_f1_clustercentroids)
print('Mean Entropy:', mean_entropy_clustercentroids)
print('Entropy Std Dev:', std_entropy_clustercentroids)
print('Mean Confusion Matrix:\n', mean_conf_matrix_clustercentroids)

# Print results after TomekLinks
print('--- After TomekLinks ---')
print('Mean Accuracy:', mean_accuracy_tomeklinks)
print('Accuracy Std Dev:', std_accuracy_tomeklinks)
print('Mean Precision:', mean_precision_tomeklinks)
print('Precision Std Dev:', std_precision_tomeklinks)
print('Mean Recall:', mean_recall_tomeklinks)
print('Recall Std Dev:', std_recall_tomeklinks)
print('Mean F1-score:', mean_f1_tomeklinks)
print('F1-score Std Dev:', std_f1_tomeklinks)
print('Mean Entropy:', mean_entropy_tomeklinks)
print('Entropy Std Dev:', std_entropy_tomeklinks)
print('Mean Confusion Matrix:\n', mean_conf_matrix_tomeklinks)

# Print results after RandomUnderSampler
print('--- After RandomUnderSampler ---')
print('Mean Accuracy:', mean_accuracy_random)
print('Accuracy Std Dev:', std_accuracy_random)
print('Mean Precision:', mean_precision_random)
print('Precision Std Dev:', std_precision_random)
print('Mean Recall:', mean_recall_random)
print('Recall Std Dev:', std_recall_random)
print('Mean F1-score:', mean_f1_random)
print('F1-score Std Dev:', std_f1_random)
print('Mean Entropy:', mean_entropy_random)
print('Entropy Std Dev:', std_entropy_random)
print('Mean Confusion Matrix:\n', mean_conf_matrix_random)
from sklearn.model_selection import StratifiedKFold
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score
from imblearn.under_sampling import NearMiss, ClusterCentroids, TomekLinks, RandomUnderSampler
import numpy as np

# Define entropy function
def calculate_entropy(probabilities):
    epsilon = 1e-10  # Small constant to avoid log(0)
    return -np.mean(np.sum(probabilities * np.log(probabilities + epsilon), axis=1))

# Number of folds
n_splits = 10

# Initialize StratifiedKFold
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)

# Initialize lists to store metrics for each fold
accuracy_list_before = []
precision_list_before = []
recall_list_before = []
f1_list_before = []
entropy_list_before = []
confusion_matrices_before = []

accuracy_list_nearmiss = []
precision_list_nearmiss = []
recall_list_nearmiss = []
f1_list_nearmiss = []
entropy_list_nearmiss = []
confusion_matrices_nearmiss = []

accuracy_list_clustercentroids = []
precision_list_clustercentroids = []
recall_list_clustercentroids = []
f1_list_clustercentroids = []
entropy_list_clustercentroids = []
confusion_matrices_clustercentroids = []

accuracy_list_tomeklinks = []
precision_list_tomeklinks = []
recall_list_tomeklinks = []
f1_list_tomeklinks = []
entropy_list_tomeklinks = []
confusion_matrices_tomeklinks = []

accuracy_list_random = []
precision_list_random = []
recall_list_random = []
f1_list_random = []
entropy_list_random = []
confusion_matrices_random = []

# Loop through the StratifiedKFold splits
for train_index, test_index in skf.split(X, y):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    
    # Initialize and train the SVM model without undersampling
    svm_model = SVC(probability=True, random_state=42)
    svm_model.fit(X_train, y_train)
    
    # Predictions and probabilities before undersampling
    y_pred_before = svm_model.predict(X_test)
    y_prob_before = svm_model.predict_proba(X_test)
    
    # Calculate entropy before undersampling
    entropy_before = calculate_entropy(y_prob_before)
    entropy_list_before.append(entropy_before)
    
    # Store metrics before undersampling
    accuracy_list_before.append(accuracy_score(y_test, y_pred_before))
    precision_list_before.append(precision_score(y_test, y_pred_before))
    recall_list_before.append(recall_score(y_test, y_pred_before))
    f1_list_before.append(f1_score(y_test, y_pred_before))
    confusion_matrices_before.append(confusion_matrix(y_test, y_pred_before))
    
    # Apply NearMiss to the training data
    nearmiss = NearMiss(version=1)
    X_train_nearmiss, y_train_nearmiss = nearmiss.fit_resample(X_train, y_train)
    
    # Initialize and train the SVM model with NearMiss
    svm_model_nearmiss = SVC(probability=True, random_state=42)
    svm_model_nearmiss.fit(X_train_nearmiss, y_train_nearmiss)
    
    # Predictions and probabilities after NearMiss
    y_pred_nearmiss = svm_model_nearmiss.predict(X_test)
    y_prob_nearmiss = svm_model_nearmiss.predict_proba(X_test)
    
    # Calculate entropy after NearMiss
    entropy_nearmiss = calculate_entropy(y_prob_nearmiss)
    entropy_list_nearmiss.append(entropy_nearmiss)
    
    # Store metrics after NearMiss
    accuracy_list_nearmiss.append(accuracy_score(y_test, y_pred_nearmiss))
    precision_list_nearmiss.append(precision_score(y_test, y_pred_nearmiss))
    recall_list_nearmiss.append(recall_score(y_test, y_pred_nearmiss))
    f1_list_nearmiss.append(f1_score(y_test, y_pred_nearmiss))
    confusion_matrices_nearmiss.append(confusion_matrix(y_test, y_pred_nearmiss))
    
    # Apply ClusterCentroids to the training data
    clustercentroids = ClusterCentroids(random_state=42)
    X_train_clustercentroids, y_train_clustercentroids = clustercentroids.fit_resample(X_train, y_train)
    
    # Initialize and train the SVM model with ClusterCentroids
    svm_model_clustercentroids = SVC(probability=True, random_state=42)
    svm_model_clustercentroids.fit(X_train_clustercentroids, y_train_clustercentroids)
    
    # Predictions and probabilities after ClusterCentroids
    y_pred_clustercentroids = svm_model_clustercentroids.predict(X_test)
    y_prob_clustercentroids = svm_model_clustercentroids.predict_proba(X_test)
    
    # Calculate entropy after ClusterCentroids
    entropy_clustercentroids = calculate_entropy(y_prob_clustercentroids)
    entropy_list_clustercentroids.append(entropy_clustercentroids)
    
    # Store metrics after ClusterCentroids
    accuracy_list_clustercentroids.append(accuracy_score(y_test, y_pred_clustercentroids))
    precision_list_clustercentroids.append(precision_score(y_test, y_pred_clustercentroids))
    recall_list_clustercentroids.append(recall_score(y_test, y_pred_clustercentroids))
    f1_list_clustercentroids.append(f1_score(y_test, y_pred_clustercentroids))
    confusion_matrices_clustercentroids.append(confusion_matrix(y_test, y_pred_clustercentroids))
    
    # Apply TomekLinks to the training data
    tomeklinks = TomekLinks()
    X_train_tomeklinks, y_train_tomeklinks = tomeklinks.fit_resample(X_train, y_train)
    
    # Initialize and train the SVM model with TomekLinks
    svm_model_tomeklinks = SVC(probability=True, random_state=42)
    svm_model_tomeklinks.fit(X_train_tomeklinks, y_train_tomeklinks)
    
    # Predictions and probabilities after TomekLinks
    y_pred_tomeklinks = svm_model_tomeklinks.predict(X_test)
    y_prob_tomeklinks = svm_model_tomeklinks.predict_proba(X_test)
    
    # Calculate entropy after TomekLinks
    entropy_tomeklinks = calculate_entropy(y_prob_tomeklinks)
    entropy_list_tomeklinks.append(entropy_tomeklinks)
    
    # Store metrics after TomekLinks
    accuracy_list_tomeklinks.append(accuracy_score(y_test, y_pred_tomeklinks))
    precision_list_tomeklinks.append(precision_score(y_test, y_pred_tomeklinks))
    recall_list_tomeklinks.append(recall_score(y_test, y_pred_tomeklinks))
    f1_list_tomeklinks.append(f1_score(y_test, y_pred_tomeklinks))
    confusion_matrices_tomeklinks.append(confusion_matrix(y_test, y_pred_tomeklinks))
    
    # Apply RandomUnderSampler to the training data
    random_undersampler = RandomUnderSampler(random_state=42)
    X_train_random, y_train_random = random_undersampler.fit_resample(X_train, y_train)
    
    # Initialize and train the SVM model with RandomUnderSampler
    svm_model_random = SVC(probability=True, random_state=42)
    svm_model_random.fit(X_train_random, y_train_random)
    
    # Predictions and probabilities after RandomUnderSampler
    y_pred_random = svm_model_random.predict(X_test)
    y_prob_random = svm_model_random.predict_proba(X_test)
    
    # Calculate entropy after RandomUnderSampler
    entropy_random = calculate_entropy(y_prob_random)
    entropy_list_random.append(entropy_random)
    
    # Store metrics after RandomUnderSampler
    accuracy_list_random.append(accuracy_score(y_test, y_pred_random))
    precision_list_random.append(precision_score(y_test, y_pred_random))
    recall_list_random.append(recall_score(y_test, y_pred_random))
    f1_list_random.append(f1_score(y_test, y_pred_random))
    confusion_matrices_random.append(confusion_matrix(y_test, y_pred_random))
    
    # Print confusion matrices for each method
    print(f'Confusion Matrix for Fold {len(confusion_matrices_before)} Before Undersampling:\n', confusion_matrices_before[-1])
    print(f'Confusion Matrix for Fold {len(confusion_matrices_nearmiss)} After NearMiss:\n', confusion_matrices_nearmiss[-1])
    print(f'Confusion Matrix for Fold {len(confusion_matrices_clustercentroids)} After ClusterCentroids:\n', confusion_matrices_clustercentroids[-1])
    print(f'Confusion Matrix for Fold {len(confusion_matrices_tomeklinks)} After TomekLinks:\n', confusion_matrices_tomeklinks[-1])
    print(f'Confusion Matrix for Fold {len(confusion_matrices_random)} After RandomUnderSampler:\n', confusion_matrices_random[-1])

# Calculate mean and standard deviation of each metric before undersampling
mean_accuracy_before = np.mean(accuracy_list_before)
std_accuracy_before = np.std(accuracy_list_before)
mean_precision_before = np.mean(precision_list_before)
std_precision_before = np.std(precision_list_before)
mean_recall_before = np.mean(recall_list_before)
std_recall_before = np.std(recall_list_before)
mean_f1_before = np.mean(f1_list_before)
std_f1_before = np.std(f1_list_before)
mean_entropy_before = np.mean(entropy_list_before)
std_entropy_before = np.std(entropy_list_before)

# Calculate mean and standard deviation of each metric after NearMiss
mean_accuracy_nearmiss = np.mean(accuracy_list_nearmiss)
std_accuracy_nearmiss = np.std(accuracy_list_nearmiss)
mean_precision_nearmiss = np.mean(precision_list_nearmiss)
std_precision_nearmiss = np.std(precision_list_nearmiss)
mean_recall_nearmiss = np.mean(recall_list_nearmiss)
std_recall_nearmiss = np.std(recall_list_nearmiss)
mean_f1_nearmiss = np.mean(f1_list_nearmiss)
std_f1_nearmiss = np.std(f1_list_nearmiss)
mean_entropy_nearmiss = np.mean(entropy_list_nearmiss)
std_entropy_nearmiss = np.std(entropy_list_nearmiss)

# Calculate mean and standard deviation of each metric after ClusterCentroids
mean_accuracy_clustercentroids = np.mean(accuracy_list_clustercentroids)
std_accuracy_clustercentroids = np.std(accuracy_list_clustercentroids)
mean_precision_clustercentroids = np.mean(precision_list_clustercentroids)
std_precision_clustercentroids = np.std(precision_list_clustercentroids)
mean_recall_clustercentroids = np.mean(recall_list_clustercentroids)
std_recall_clustercentroids = np.std(recall_list_clustercentroids)
mean_f1_clustercentroids = np.mean(f1_list_clustercentroids)
std_f1_clustercentroids = np.std(f1_list_clustercentroids)
mean_entropy_clustercentroids = np.mean(entropy_list_clustercentroids)
std_entropy_clustercentroids = np.std(entropy_list_clustercentroids)

# Calculate mean and standard deviation of each metric after TomekLinks
mean_accuracy_tomeklinks = np.mean(accuracy_list_tomeklinks)
std_accuracy_tomeklinks = np.std(accuracy_list_tomeklinks)
mean_precision_tomeklinks = np.mean(precision_list_tomeklinks)
std_precision_tomeklinks = np.std(precision_list_tomeklinks)
mean_recall_tomeklinks = np.mean(recall_list_tomeklinks)
std_recall_tomeklinks = np.std(recall_list_tomeklinks)
mean_f1_tomeklinks = np.mean(f1_list_tomeklinks)
std_f1_tomeklinks = np.std(f1_list_tomeklinks)
mean_entropy_tomeklinks = np.mean(entropy_list_tomeklinks)
std_entropy_tomeklinks = np.std(entropy_list_tomeklinks)

# Calculate mean and standard deviation of each metric after RandomUnderSampler
mean_accuracy_random = np.mean(accuracy_list_random)
std_accuracy_random = np.std(accuracy_list_random)
mean_precision_random = np.mean(precision_list_random)
std_precision_random = np.std(precision_list_random)
mean_recall_random = np.mean(recall_list_random)
std_recall_random = np.std(recall_list_random)
mean_f1_random = np.mean(f1_list_random)
std_f1_random = np.std(f1_list_random)
mean_entropy_random = np.mean(entropy_list_random)
std_entropy_random = np.std(entropy_list_random)

# Calculate mean confusion matrix before and after each method
mean_conf_matrix_before = np.mean(confusion_matrices_before, axis=0)
mean_conf_matrix_nearmiss = np.mean(confusion_matrices_nearmiss, axis=0)
mean_conf_matrix_clustercentroids = np.mean(confusion_matrices_clustercentroids, axis=0)
mean_conf_matrix_tomeklinks = np.mean(confusion_matrices_tomeklinks, axis=0)
mean_conf_matrix_random = np.mean(confusion_matrices_random, axis=0)

# Print results before undersampling
print('--- Before Undersampling ---')
print('Mean Accuracy:', mean_accuracy_before)
print('Accuracy Std Dev:', std_accuracy_before)
print('Mean Precision:', mean_precision_before)
print('Precision Std Dev:', std_precision_before)
print('Mean Recall:', mean_recall_before)
print('Recall Std Dev:', std_recall_before)
print('Mean F1-score:', mean_f1_before)
print('F1-score Std Dev:', std_f1_before)
print('Mean Entropy:', mean_entropy_before)
print('Entropy Std Dev:', std_entropy_before)
print('Mean Confusion Matrix:\n', mean_conf_matrix_before)

# Print results after NearMiss
print('--- After NearMiss ---')
print('Mean Accuracy:', mean_accuracy_nearmiss)
print('Accuracy Std Dev:', std_accuracy_nearmiss)
print('Mean Precision:', mean_precision_nearmiss)
print('Precision Std Dev:', std_precision_nearmiss)
print('Mean Recall:', mean_recall_nearmiss)
print('Recall Std Dev:', std_recall_nearmiss)
print('Mean F1-score:', mean_f1_nearmiss)
print('F1-score Std Dev:', std_f1_nearmiss)
print('Mean Entropy:', mean_entropy_nearmiss)
print('Entropy Std Dev:', std_entropy_nearmiss)
print('Mean Confusion Matrix:\n', mean_conf_matrix_nearmiss)

# Print results after ClusterCentroids
print('--- After ClusterCentroids ---')
print('Mean Accuracy:', mean_accuracy_clustercentroids)
print('Accuracy Std Dev:', std_accuracy_clustercentroids)
print('Mean Precision:', mean_precision_clustercentroids)
print('Precision Std Dev:', std_precision_clustercentroids)
print('Mean Recall:', mean_recall_clustercentroids)
print('Recall Std Dev:', std_recall_clustercentroids)
print('Mean F1-score:', mean_f1_clustercentroids)
print('F1-score Std Dev:', std_f1_clustercentroids)
print('Mean Entropy:', mean_entropy_clustercentroids)
print('Entropy Std Dev:', std_entropy_clustercentroids)
print('Mean Confusion Matrix:\n', mean_conf_matrix_clustercentroids)

# Print results after TomekLinks
print('--- After TomekLinks ---')
print('Mean Accuracy:', mean_accuracy_tomeklinks)
print('Accuracy Std Dev:', std_accuracy_tomeklinks)
print('Mean Precision:', mean_precision_tomeklinks)
print('Precision Std Dev:', std_precision_tomeklinks)
print('Mean Recall:', mean_recall_tomeklinks)
print('Recall Std Dev:', std_recall_tomeklinks)
print('Mean F1-score:', mean_f1_tomeklinks)
print('F1-score Std Dev:', std_f1_tomeklinks)
print('Mean Entropy:', mean_entropy_tomeklinks)
print('Entropy Std Dev:', std_entropy_tomeklinks)
print('Mean Confusion Matrix:\n', mean_conf_matrix_tomeklinks)

# Print results after RandomUnderSampler
print('--- After RandomUnderSampler ---')
print('Mean Accuracy:', mean_accuracy_random)
print('Accuracy Std Dev:', std_accuracy_random)
print('Mean Precision:', mean_precision_random)
print('Precision Std Dev:', std_precision_random)
print('Mean Recall:', mean_recall_random)
print('Recall Std Dev:', std_recall_random)
print('Mean F1-score:', mean_f1_random)
print('F1-score Std Dev:', std_f1_random)
print('Mean Entropy:', mean_entropy_random)
print('Entropy Std Dev:', std_entropy_random)
print('Mean Confusion Matrix:\n', mean_conf_matrix_random)


/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Confusion Matrix for Fold 1 Before Undersampling:
 [[81  0]
 [ 5  0]]
Confusion Matrix for Fold 1 After NearMiss:
 [[23 58]
 [ 1  4]]
Confusion Matrix for Fold 1 After ClusterCentroids:
 [[18 63]
 [ 2  3]]
Confusion Matrix for Fold 1 After TomekLinks:
 [[81  0]
 [ 5  0]]
Confusion Matrix for Fold 1 After RandomUnderSampler:
 [[36 45]
 [ 2  3]]
Confusion Matrix for Fold 2 Before Undersampling:
 [[81  0]
 [ 5  0]]
Confusion Matrix for Fold 2 After NearMiss:
 [[35 46]
 [ 0  5]]
Confusion Matrix for Fold 2 After ClusterCentroids:
 [[24 57]
 [ 3  2]]
Confusion Matrix for Fold 2 After TomekLinks:
 [[81  0]
 [ 5  0]]
Confusion Matrix for Fold 2 After RandomUnderSampler:
 [[70 11]
 [ 4  1]]


/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Confusion Matrix for Fold 3 Before Undersampling:
 [[81  0]
 [ 5  0]]
Confusion Matrix for Fold 3 After NearMiss:
 [[37 44]
 [ 1  4]]
Confusion Matrix for Fold 3 After ClusterCentroids:
 [[23 58]
 [ 1  4]]
Confusion Matrix for Fold 3 After TomekLinks:
 [[81  0]
 [ 5  0]]
Confusion Matrix for Fold 3 After RandomUnderSampler:
 [[24 57]
 [ 1  4]]
Confusion Matrix for Fold 4 Before Undersampling:
 [[80  0]
 [ 6  0]]
Confusion Matrix for Fold 4 After NearMiss:
 [[39 41]
 [ 3  3]]
Confusion Matrix for Fold 4 After ClusterCentroids:
 [[ 6 74]
 [ 1  5]]
Confusion Matrix for Fold 4 After TomekLinks:
 [[80  0]
 [ 6  0]]
Confusion Matrix for Fold 4 After RandomUnderSampler:
 [[59 21]
 [ 5  1]]


/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/amin/opt/anaconda3/lib/p

Confusion Matrix for Fold 5 Before Undersampling:
 [[80  0]
 [ 6  0]]
Confusion Matrix for Fold 5 After NearMiss:
 [[31 49]
 [ 2  4]]
Confusion Matrix for Fold 5 After ClusterCentroids:
 [[10 70]
 [ 0  6]]
Confusion Matrix for Fold 5 After TomekLinks:
 [[80  0]
 [ 6  0]]
Confusion Matrix for Fold 5 After RandomUnderSampler:
 [[26 54]
 [ 1  5]]
Confusion Matrix for Fold 6 Before Undersampling:
 [[80  0]
 [ 6  0]]
Confusion Matrix for Fold 6 After NearMiss:
 [[26 54]
 [ 2  4]]
Confusion Matrix for Fold 6 After ClusterCentroids:
 [[ 8 72]
 [ 2  4]]
Confusion Matrix for Fold 6 After TomekLinks:
 [[80  0]
 [ 6  0]]
Confusion Matrix for Fold 6 After RandomUnderSampler:
 [[66 14]
 [ 3  3]]


/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Confusion Matrix for Fold 7 Before Undersampling:
 [[80  0]
 [ 6  0]]
Confusion Matrix for Fold 7 After NearMiss:
 [[30 50]
 [ 2  4]]
Confusion Matrix for Fold 7 After ClusterCentroids:
 [[11 69]
 [ 1  5]]
Confusion Matrix for Fold 7 After TomekLinks:
 [[80  0]
 [ 6  0]]
Confusion Matrix for Fold 7 After RandomUnderSampler:
 [[30 50]
 [ 4  2]]
Confusion Matrix for Fold 8 Before Undersampling:
 [[80  0]
 [ 6  0]]
Confusion Matrix for Fold 8 After NearMiss:
 [[35 45]
 [ 2  4]]
Confusion Matrix for Fold 8 After ClusterCentroids:
 [[18 62]
 [ 3  3]]
Confusion Matrix for Fold 8 After TomekLinks:
 [[80  0]
 [ 6  0]]
Confusion Matrix for Fold 8 After RandomUnderSampler:
 [[11 69]
 [ 2  4]]


/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Confusion Matrix for Fold 9 Before Undersampling:
 [[80  0]
 [ 5  0]]
Confusion Matrix for Fold 9 After NearMiss:
 [[31 49]
 [ 2  3]]
Confusion Matrix for Fold 9 After ClusterCentroids:
 [[18 62]
 [ 1  4]]
Confusion Matrix for Fold 9 After TomekLinks:
 [[80  0]
 [ 5  0]]
Confusion Matrix for Fold 9 After RandomUnderSampler:
 [[66 14]
 [ 3  2]]
Confusion Matrix for Fold 10 Before Undersampling:
 [[80  0]
 [ 5  0]]
Confusion Matrix for Fold 10 After NearMiss:
 [[26 54]
 [ 1  4]]
Confusion Matrix for Fold 10 After ClusterCentroids:
 [[14 66]
 [ 1  4]]
Confusion Matrix for Fold 10 After TomekLinks:
 [[80  0]
 [ 5  0]]
Confusion Matrix for Fold 10 After RandomUnderSampler:
 [[37 43]
 [ 2  3]]
--- Before Undersampling ---
Mean Accuracy: 0.9359097127222983
Accuracy Std Dev: 0.005682096970161464
Mean Precision: 0.0
Precision Std Dev: 0.0
Mean Recall: 0.0
Recall Std Dev: 0.0
Mean F1-score: 0.0
F1-score Std Dev: 0.0
Mean Entropy: 0.22670256740313155
Entropy Std Dev: 0.00942586759892498
Mean Conf

/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/amin/opt/anaconda3/lib/p

Confusion Matrix for Fold 1 Before Undersampling:
 [[81  0]
 [ 5  0]]
Confusion Matrix for Fold 1 After NearMiss:
 [[23 58]
 [ 1  4]]
Confusion Matrix for Fold 1 After ClusterCentroids:
 [[18 63]
 [ 2  3]]
Confusion Matrix for Fold 1 After TomekLinks:
 [[81  0]
 [ 5  0]]
Confusion Matrix for Fold 1 After RandomUnderSampler:
 [[36 45]
 [ 2  3]]
Confusion Matrix for Fold 2 Before Undersampling:
 [[81  0]
 [ 5  0]]
Confusion Matrix for Fold 2 After NearMiss:
 [[35 46]
 [ 0  5]]
Confusion Matrix for Fold 2 After ClusterCentroids:
 [[24 57]
 [ 3  2]]
Confusion Matrix for Fold 2 After TomekLinks:
 [[81  0]
 [ 5  0]]
Confusion Matrix for Fold 2 After RandomUnderSampler:
 [[70 11]
 [ 4  1]]


/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Confusion Matrix for Fold 3 Before Undersampling:
 [[81  0]
 [ 5  0]]
Confusion Matrix for Fold 3 After NearMiss:
 [[37 44]
 [ 1  4]]
Confusion Matrix for Fold 3 After ClusterCentroids:
 [[23 58]
 [ 1  4]]
Confusion Matrix for Fold 3 After TomekLinks:
 [[81  0]
 [ 5  0]]
Confusion Matrix for Fold 3 After RandomUnderSampler:
 [[24 57]
 [ 1  4]]
Confusion Matrix for Fold 4 Before Undersampling:
 [[80  0]
 [ 6  0]]
Confusion Matrix for Fold 4 After NearMiss:
 [[39 41]
 [ 3  3]]
Confusion Matrix for Fold 4 After ClusterCentroids:
 [[ 6 74]
 [ 1  5]]
Confusion Matrix for Fold 4 After TomekLinks:
 [[80  0]
 [ 6  0]]
Confusion Matrix for Fold 4 After RandomUnderSampler:
 [[59 21]
 [ 5  1]]


/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Confusion Matrix for Fold 5 Before Undersampling:
 [[80  0]
 [ 6  0]]
Confusion Matrix for Fold 5 After NearMiss:
 [[31 49]
 [ 2  4]]
Confusion Matrix for Fold 5 After ClusterCentroids:
 [[10 70]
 [ 0  6]]
Confusion Matrix for Fold 5 After TomekLinks:
 [[80  0]
 [ 6  0]]
Confusion Matrix for Fold 5 After RandomUnderSampler:
 [[26 54]
 [ 1  5]]
Confusion Matrix for Fold 6 Before Undersampling:
 [[80  0]
 [ 6  0]]
Confusion Matrix for Fold 6 After NearMiss:
 [[26 54]
 [ 2  4]]
Confusion Matrix for Fold 6 After ClusterCentroids:
 [[ 8 72]
 [ 2  4]]
Confusion Matrix for Fold 6 After TomekLinks:
 [[80  0]
 [ 6  0]]
Confusion Matrix for Fold 6 After RandomUnderSampler:
 [[66 14]
 [ 3  3]]


/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/amin/opt/anaconda3/lib/p

Confusion Matrix for Fold 7 Before Undersampling:
 [[80  0]
 [ 6  0]]
Confusion Matrix for Fold 7 After NearMiss:
 [[30 50]
 [ 2  4]]
Confusion Matrix for Fold 7 After ClusterCentroids:
 [[11 69]
 [ 1  5]]
Confusion Matrix for Fold 7 After TomekLinks:
 [[80  0]
 [ 6  0]]
Confusion Matrix for Fold 7 After RandomUnderSampler:
 [[30 50]
 [ 4  2]]
Confusion Matrix for Fold 8 Before Undersampling:
 [[80  0]
 [ 6  0]]
Confusion Matrix for Fold 8 After NearMiss:
 [[35 45]
 [ 2  4]]
Confusion Matrix for Fold 8 After ClusterCentroids:
 [[18 62]
 [ 3  3]]
Confusion Matrix for Fold 8 After TomekLinks:
 [[80  0]
 [ 6  0]]
Confusion Matrix for Fold 8 After RandomUnderSampler:
 [[11 69]
 [ 2  4]]


/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Confusion Matrix for Fold 9 Before Undersampling:
 [[80  0]
 [ 5  0]]
Confusion Matrix for Fold 9 After NearMiss:
 [[31 49]
 [ 2  3]]
Confusion Matrix for Fold 9 After ClusterCentroids:
 [[18 62]
 [ 1  4]]
Confusion Matrix for Fold 9 After TomekLinks:
 [[80  0]
 [ 5  0]]
Confusion Matrix for Fold 9 After RandomUnderSampler:
 [[66 14]
 [ 3  2]]
Confusion Matrix for Fold 10 Before Undersampling:
 [[80  0]
 [ 5  0]]
Confusion Matrix for Fold 10 After NearMiss:
 [[26 54]
 [ 1  4]]
Confusion Matrix for Fold 10 After ClusterCentroids:
 [[14 66]
 [ 1  4]]
Confusion Matrix for Fold 10 After TomekLinks:
 [[80  0]
 [ 5  0]]
Confusion Matrix for Fold 10 After RandomUnderSampler:
 [[37 43]
 [ 2  3]]
--- Before Undersampling ---
Mean Accuracy: 0.9359097127222983
Accuracy Std Dev: 0.005682096970161464
Mean Precision: 0.0
Precision Std Dev: 0.0
Mean Recall: 0.0
Recall Std Dev: 0.0
Mean F1-score: 0.0
F1-score Std Dev: 0.0
Mean Entropy: 0.22670256740313155
Entropy Std Dev: 0.00942586759892498
Mean Conf

/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [6]:
from sklearn.model_selection import StratifiedKFold
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score
from imblearn.over_sampling import SMOTE, ADASYN, RandomOverSampler
import numpy as np

# Number of folds
n_splits = 10

# Initialize StratifiedKFold
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)

# Initialize lists to store metrics for each fold
accuracy_list = []
precision_list = []
recall_list = []
f1_list = []
uncertainty_list = []  # List to store entropy for each fold
confusion_matrices = []

# Choose an oversampling method
oversampler = SMOTE(random_state=42)
# oversampler = ADASYN(random_state=42)
#oversampler = RandomOverSampler(random_state=42)

# Function to calculate entropy
def calculate_entropy(probabilities):
    entropy = -np.sum(probabilities * np.log(probabilities + 1e-9), axis=1)  # Add small value to avoid log(0)
    return np.mean(entropy)

# Loop through the StratifiedKFold splits
for train_index, test_index in skf.split(X, y):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    
    # Apply oversampling
    X_train_resampled, y_train_resampled = oversampler.fit_resample(X_train, y_train)
    
    # Initialize and train the SVM model with probability enabled
    svm_model = SVC(probability=True, random_state=42)
    svm_model.fit(X_train_resampled, y_train_resampled)
    
    # Predict probabilities and classes
    y_pred_svm = svm_model.predict(X_test)
    y_prob_svm = svm_model.predict_proba(X_test)
    
    # Calculate and store entropy
    entropy = calculate_entropy(y_prob_svm)
    uncertainty_list.append(entropy)
    
    # Store metrics
    accuracy_list.append(accuracy_score(y_test, y_pred_svm))
    precision_list.append(precision_score(y_test, y_pred_svm))
    recall_list.append(recall_score(y_test, y_pred_svm))
    f1_list.append(f1_score(y_test, y_pred_svm))
    
    # Store confusion matrix
    conf_matrix = confusion_matrix(y_test, y_pred_svm)
    confusion_matrices.append(conf_matrix)
    print(f'Confusion Matrix for Fold {len(confusion_matrices)}:\n', conf_matrix)

# Calculate mean and standard deviation of each metric
mean_accuracy = np.mean(accuracy_list)
std_accuracy = np.std(accuracy_list)
mean_precision = np.mean(precision_list)
std_precision = np.std(precision_list)
mean_recall = np.mean(recall_list)
std_recall = np.std(recall_list)
mean_f1 = np.mean(f1_list)
std_f1 = np.std(f1_list)

# Calculate mean and standard deviation of entropy
mean_entropy = np.mean(uncertainty_list)
std_entropy = np.std(uncertainty_list)

# Calculate mean confusion matrix
mean_conf_matrix = np.mean(confusion_matrices, axis=0)

# Print results
print('Mean Accuracy:', mean_accuracy)
print('Accuracy Std Dev:', std_accuracy)
print('Mean Precision:', mean_precision)
print('Precision Std Dev:', std_precision)
print('Mean Recall:', mean_recall)
print('Recall Std Dev:', std_recall)
print('Mean F1-score:', mean_f1)
print('F1-score Std Dev:', std_f1)
print('Mean Entropy:', mean_entropy)
print('Entropy Std Dev:', std_entropy)
print('Mean Confusion Matrix:\n', mean_conf_matrix)


Confusion Matrix for Fold 1:
 [[66 15]
 [ 4  1]]
Confusion Matrix for Fold 2:
 [[67 14]
 [ 4  1]]
Confusion Matrix for Fold 3:
 [[60 21]
 [ 3  2]]
Confusion Matrix for Fold 4:
 [[70 10]
 [ 4  2]]
Confusion Matrix for Fold 5:
 [[64 16]
 [ 1  5]]
Confusion Matrix for Fold 6:
 [[65 15]
 [ 5  1]]
Confusion Matrix for Fold 7:
 [[56 24]
 [ 3  3]]
Confusion Matrix for Fold 8:
 [[62 18]
 [ 3  3]]
Confusion Matrix for Fold 9:
 [[65 15]
 [ 3  2]]
Confusion Matrix for Fold 10:
 [[65 15]
 [ 1  4]]
Mean Accuracy: 0.773953488372093
Accuracy Std Dev: 0.04202025954880806
Mean Precision: 0.1265526721748959
Precision Std Dev: 0.05919942172024951
Mean Recall: 0.4333333333333333
Recall Std Dev: 0.22261077142752
Mean F1-score: 0.19407888407888407
F1-score Std Dev: 0.0917841191842333
Mean Entropy: 0.510744657641474
Entropy Std Dev: 0.02766867542750917
Mean Confusion Matrix:
 [[64.  16.3]
 [ 3.1  2.4]]


In [8]:
from sklearn.model_selection import StratifiedKFold
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score
from imblearn.over_sampling import SMOTE, ADASYN, RandomOverSampler
import numpy as np

# Number of folds
n_splits = 10

# Initialize StratifiedKFold
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)

# Initialize lists to store metrics for each fold
accuracy_list = []
precision_list = []
recall_list = []
f1_list = []
uncertainty_list = []  # List to store entropy for each fold
confusion_matrices = []

# Choose an oversampling method
#oversampler = SMOTE(random_state=42)
oversampler = ADASYN(random_state=42)
#oversampler = RandomOverSampler(random_state=42)

# Function to calculate entropy
def calculate_entropy(probabilities):
    entropy = -np.sum(probabilities * np.log(probabilities + 1e-9), axis=1)  # Add small value to avoid log(0)
    return np.mean(entropy)

# Loop through the StratifiedKFold splits
for train_index, test_index in skf.split(X, y):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    
    # Apply oversampling
    X_train_resampled, y_train_resampled = oversampler.fit_resample(X_train, y_train)
    
    # Initialize and train the SVM model with probability enabled
    svm_model = SVC(probability=True, random_state=42)
    svm_model.fit(X_train_resampled, y_train_resampled)
    
    # Predict probabilities and classes
    y_pred_svm = svm_model.predict(X_test)
    y_prob_svm = svm_model.predict_proba(X_test)
    
    # Calculate and store entropy
    entropy = calculate_entropy(y_prob_svm)
    uncertainty_list.append(entropy)
    
    # Store metrics
    accuracy_list.append(accuracy_score(y_test, y_pred_svm))
    precision_list.append(precision_score(y_test, y_pred_svm))
    recall_list.append(recall_score(y_test, y_pred_svm))
    f1_list.append(f1_score(y_test, y_pred_svm))
    
    # Store confusion matrix
    conf_matrix = confusion_matrix(y_test, y_pred_svm)
    confusion_matrices.append(conf_matrix)
    print(f'Confusion Matrix for Fold {len(confusion_matrices)}:\n', conf_matrix)

# Calculate mean and standard deviation of each metric
mean_accuracy = np.mean(accuracy_list)
std_accuracy = np.std(accuracy_list)
mean_precision = np.mean(precision_list)
std_precision = np.std(precision_list)
mean_recall = np.mean(recall_list)
std_recall = np.std(recall_list)
mean_f1 = np.mean(f1_list)
std_f1 = np.std(f1_list)

# Calculate mean and standard deviation of entropy
mean_entropy = np.mean(uncertainty_list)
std_entropy = np.std(uncertainty_list)

# Calculate mean confusion matrix
mean_conf_matrix = np.mean(confusion_matrices, axis=0)

# Print results
print('Mean Accuracy:', mean_accuracy)
print('Accuracy Std Dev:', std_accuracy)
print('Mean Precision:', mean_precision)
print('Precision Std Dev:', std_precision)
print('Mean Recall:', mean_recall)
print('Recall Std Dev:', std_recall)
print('Mean F1-score:', mean_f1)
print('F1-score Std Dev:', std_f1)
print('Mean Entropy:', mean_entropy)
print('Entropy Std Dev:', std_entropy)
print('Mean Confusion Matrix:\n', mean_conf_matrix)


Confusion Matrix for Fold 1:
 [[65 16]
 [ 4  1]]
Confusion Matrix for Fold 2:
 [[65 16]
 [ 4  1]]
Confusion Matrix for Fold 3:
 [[65 16]
 [ 3  2]]
Confusion Matrix for Fold 4:
 [[69 11]
 [ 3  3]]
Confusion Matrix for Fold 5:
 [[67 13]
 [ 3  3]]
Confusion Matrix for Fold 6:
 [[65 15]
 [ 5  1]]
Confusion Matrix for Fold 7:
 [[57 23]
 [ 5  1]]
Confusion Matrix for Fold 8:
 [[63 17]
 [ 3  3]]
Confusion Matrix for Fold 9:
 [[64 16]
 [ 3  2]]
Confusion Matrix for Fold 10:
 [[70 10]
 [ 1  4]]
Mean Accuracy: 0.7821477428180575
Accuracy Std Dev: 0.04937349959738104
Mean Precision: 0.12815359477124183
Precision Std Dev: 0.07630725145159051
Mean Recall: 0.3833333333333333
Recall Std Dev: 0.1939358427705181
Mean F1-score: 0.1911769161425912
F1-score Std Dev: 0.10916185932763393
Mean Entropy: 0.49089675261523363
Entropy Std Dev: 0.03879538766884343
Mean Confusion Matrix:
 [[65.  15.3]
 [ 3.4  2.1]]


In [9]:
from sklearn.model_selection import StratifiedKFold
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score
from imblearn.over_sampling import SMOTE, ADASYN, RandomOverSampler
import numpy as np

# Number of folds
n_splits = 10

# Initialize StratifiedKFold
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)

# Initialize lists to store metrics for each fold
accuracy_list = []
precision_list = []
recall_list = []
f1_list = []
uncertainty_list = []  # List to store entropy for each fold
confusion_matrices = []

# Choose an oversampling method
#oversampler = SMOTE(random_state=42)
#oversampler = ADASYN(random_state=42)
oversampler = RandomOverSampler(random_state=42)

# Function to calculate entropy
def calculate_entropy(probabilities):
    entropy = -np.sum(probabilities * np.log(probabilities + 1e-9), axis=1)  # Add small value to avoid log(0)
    return np.mean(entropy)

# Loop through the StratifiedKFold splits
for train_index, test_index in skf.split(X, y):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    
    # Apply oversampling
    X_train_resampled, y_train_resampled = oversampler.fit_resample(X_train, y_train)
    
    # Initialize and train the SVM model with probability enabled
    svm_model = SVC(probability=True, random_state=42)
    svm_model.fit(X_train_resampled, y_train_resampled)
    
    # Predict probabilities and classes
    y_pred_svm = svm_model.predict(X_test)
    y_prob_svm = svm_model.predict_proba(X_test)
    
    # Calculate and store entropy
    entropy = calculate_entropy(y_prob_svm)
    uncertainty_list.append(entropy)
    
    # Store metrics
    accuracy_list.append(accuracy_score(y_test, y_pred_svm))
    precision_list.append(precision_score(y_test, y_pred_svm))
    recall_list.append(recall_score(y_test, y_pred_svm))
    f1_list.append(f1_score(y_test, y_pred_svm))
    
    # Store confusion matrix
    conf_matrix = confusion_matrix(y_test, y_pred_svm)
    confusion_matrices.append(conf_matrix)
    print(f'Confusion Matrix for Fold {len(confusion_matrices)}:\n', conf_matrix)

# Calculate mean and standard deviation of each metric
mean_accuracy = np.mean(accuracy_list)
std_accuracy = np.std(accuracy_list)
mean_precision = np.mean(precision_list)
std_precision = np.std(precision_list)
mean_recall = np.mean(recall_list)
std_recall = np.std(recall_list)
mean_f1 = np.mean(f1_list)
std_f1 = np.std(f1_list)

# Calculate mean and standard deviation of entropy
mean_entropy = np.mean(uncertainty_list)
std_entropy = np.std(uncertainty_list)

# Calculate mean confusion matrix
mean_conf_matrix = np.mean(confusion_matrices, axis=0)

# Print results
print('Mean Accuracy:', mean_accuracy)
print('Accuracy Std Dev:', std_accuracy)
print('Mean Precision:', mean_precision)
print('Precision Std Dev:', std_precision)
print('Mean Recall:', mean_recall)
print('Recall Std Dev:', std_recall)
print('Mean F1-score:', mean_f1)
print('F1-score Std Dev:', std_f1)
print('Mean Entropy:', mean_entropy)
print('Entropy Std Dev:', std_entropy)
print('Mean Confusion Matrix:\n', mean_conf_matrix)


Confusion Matrix for Fold 1:
 [[71 10]
 [ 3  2]]
Confusion Matrix for Fold 2:
 [[72  9]
 [ 3  2]]
Confusion Matrix for Fold 3:
 [[73  8]
 [ 3  2]]
Confusion Matrix for Fold 4:
 [[68 12]
 [ 5  1]]
Confusion Matrix for Fold 5:
 [[66 14]
 [ 4  2]]
Confusion Matrix for Fold 6:
 [[70 10]
 [ 3  3]]
Confusion Matrix for Fold 7:
 [[61 19]
 [ 3  3]]
Confusion Matrix for Fold 8:
 [[68 12]
 [ 4  2]]
Confusion Matrix for Fold 9:
 [[72  8]
 [ 3  2]]
Confusion Matrix for Fold 10:
 [[73  7]
 [ 1  4]]
Mean Accuracy: 0.8357865937072504
Accuracy Std Dev: 0.04518007069505705
Mean Precision: 0.1824034299034299
Precision Std Dev: 0.07359125205588399
Mean Recall: 0.42333333333333334
Recall Std Dev: 0.154236470683457
Mean F1-score: 0.2535783978663236
F1-score Std Dev: 0.09840988164983558
Mean Entropy: 0.4861311151265143
Entropy Std Dev: 0.030872595523496103
Mean Confusion Matrix:
 [[69.4 10.9]
 [ 3.2  2.3]]


In [10]:
from sklearn.model_selection import StratifiedKFold
from sklearn.calibration import CalibratedClassifierCV
from sklearn.metrics import f1_score, accuracy_score, precision_score, recall_score, confusion_matrix, roc_auc_score
from sklearn.svm import SVC
import numpy as np

# Define entropy function
def calculate_entropy(probabilities):
    epsilon = 1e-10  # Small constant to avoid log(0)
    return -np.mean(np.sum(probabilities * np.log(probabilities + epsilon), axis=1))

# Function to find the best threshold for F1-score
def find_best_threshold(y_true, y_prob, thresholds):
    best_f1 = 0
    best_threshold = 0.5
    for threshold in thresholds:
        y_pred = (y_prob[:, 1] >= threshold).astype(int)
        f1 = f1_score(y_true, y_pred)
        if f1 > best_f1:
            best_f1 = f1
            best_threshold = threshold
    return best_threshold, best_f1

# Number of folds
n_splits = 10

# Initialize StratifiedKFold
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)

# Initialize lists to store metrics
best_thresholds = []
f1_list = []
accuracy_list = []
precision_list = []
recall_list = []
roc_auc_list = []
entropy_list = []
confusion_matrices = []

# Loop through the StratifiedKFold splits
for train_index, test_index in skf.split(X, y):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    
    # Initialize and train the SVM model with probability estimation
    svm_model = SVC(probability=True, random_state=42)
    svm_model.fit(X_train, y_train)
    
    # Calibrate the model
    calibrated_model = CalibratedClassifierCV(svm_model, method='isotonic', cv=5)
    calibrated_model.fit(X_train, y_train)
    
    # Get predicted probabilities on training set
    y_prob_train = calibrated_model.predict_proba(X_train)
    
    # Define a range of thresholds to test
    thresholds = np.arange(0.1, 0.9, 0.01)
    
    # Find the best threshold based on training set
    best_threshold, _ = find_best_threshold(y_train, y_prob_train, thresholds)
    best_thresholds.append(best_threshold)
    
    # Get predicted probabilities on test set
    y_prob_test = calibrated_model.predict_proba(X_test)
    
    # Calculate entropy
    entropy = calculate_entropy(y_prob_test)
    entropy_list.append(entropy)
    
    # Make predictions using the best threshold
    y_pred = (y_prob_test[:, 1] >= best_threshold).astype(int)
    
    # Calculate and store ROC AUC
    roc_auc = roc_auc_score(y_test, y_prob_test[:, 1])
    roc_auc_list.append(roc_auc)
    
    # Store the metrics
    f1_list.append(f1_score(y_test, y_pred))
    accuracy_list.append(accuracy_score(y_test, y_pred))
    precision_list.append(precision_score(y_test, y_pred))
    recall_list.append(recall_score(y_test, y_pred))
    confusion_matrices.append(confusion_matrix(y_test, y_pred))
    
    print(f'Best Threshold for Fold {len(best_thresholds)}: {best_threshold}')
    print(f'Confusion Matrix for Fold {len(best_thresholds)}:\n', confusion_matrices[-1])

# Calculate mean and standard deviation of each metric
mean_accuracy = np.mean(accuracy_list)
std_accuracy = np.std(accuracy_list)
mean_precision = np.mean(precision_list)
std_precision = np.std(precision_list)
mean_recall = np.mean(recall_list)
std_recall = np.std(recall_list)
mean_f1 = np.mean(f1_list)
std_f1 = np.std(f1_list)
mean_roc_auc = np.mean(roc_auc_list)
std_roc_auc = np.std(roc_auc_list)
mean_entropy = np.mean(entropy_list)
std_entropy = np.std(entropy_list)

# Calculate mean confusion matrix
mean_conf_matrix = np.mean(confusion_matrices, axis=0).astype(int)

# Print the results
print('--- Overall Results ---')
print('Mean Accuracy:', mean_accuracy)
print('Accuracy Std Dev:', std_accuracy)
print('Mean Precision:', mean_precision)
print('Precision Std Dev:', std_precision)
print('Mean Recall:', mean_recall)
print('Recall Std Dev:', std_recall)
print('Mean F1-score:', mean_f1)
print('F1-score Std Dev:', std_f1)
print('Mean ROC AUC:', mean_roc_auc)
print('ROC AUC Std Dev:', std_roc_auc)
print('Mean Entropy:', mean_entropy)
print('Entropy Std Dev:', std_entropy)
print('Mean Confusion Matrix:\n', mean_conf_matrix)

Best Threshold for Fold 1: 0.21999999999999995
Confusion Matrix for Fold 1:
 [[74  7]
 [ 3  2]]
Best Threshold for Fold 2: 0.2599999999999999
Confusion Matrix for Fold 2:
 [[78  3]
 [ 3  2]]
Best Threshold for Fold 3: 0.33999999999999986
Confusion Matrix for Fold 3:
 [[78  3]
 [ 3  2]]
Best Threshold for Fold 4: 0.29999999999999993
Confusion Matrix for Fold 4:
 [[79  1]
 [ 2  4]]
Best Threshold for Fold 5: 0.18999999999999995
Confusion Matrix for Fold 5:
 [[74  6]
 [ 1  5]]
Best Threshold for Fold 6: 0.2899999999999999
Confusion Matrix for Fold 6:
 [[77  3]
 [ 3  3]]
Best Threshold for Fold 7: 0.2899999999999999
Confusion Matrix for Fold 7:
 [[77  3]
 [ 2  4]]
Best Threshold for Fold 8: 0.2799999999999999
Confusion Matrix for Fold 8:
 [[77  3]
 [ 4  2]]
Best Threshold for Fold 9: 0.19999999999999996
Confusion Matrix for Fold 9:
 [[77  3]
 [ 2  3]]
Best Threshold for Fold 10: 0.2599999999999999
Confusion Matrix for Fold 10:
 [[75  5]
 [ 1  4]]
--- Overall Results ---
Mean Accuracy: 0.92

In [11]:
from sklearn.svm import SVC
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score
from imblearn.combine import SMOTETomek  # Import SMOTE + Tomek Links
import numpy as np

# Define entropy function
def calculate_entropy(probabilities):
    epsilon = 1e-10  # Small constant to avoid log(0)
    return -np.mean(np.sum(probabilities * np.log(probabilities + epsilon), axis=1))

# Number of folds
n_splits = 10

# Initialize StratifiedKFold
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)

# Initialize lists to store metrics for each fold
accuracy_list_before = []
precision_list_before = []
recall_list_before = []
f1_list_before = []
entropy_list_before = []
confusion_matrices_before = []

accuracy_list_smote_tomek = []
precision_list_smote_tomek = []
recall_list_smote_tomek = []
f1_list_smote_tomek = []
entropy_list_smote_tomek = []
confusion_matrices_smote_tomek = []

# Loop through the StratifiedKFold splits
for train_index, test_index in skf.split(X, y):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    
    # Initialize and train the SVM model without SMOTE + Tomek Links
    svm_model = SVC(probability=True, kernel='rbf', random_state=42)
    svm_model.fit(X_train, y_train)
    
    # Predictions and probabilities before SMOTE + Tomek Links
    y_pred_before = svm_model.predict(X_test)
    y_prob_before = svm_model.predict_proba(X_test)
    
    # Calculate entropy before SMOTE + Tomek Links
    entropy_before = calculate_entropy(y_prob_before)
    entropy_list_before.append(entropy_before)
    
    # Store metrics before SMOTE + Tomek Links
    accuracy_list_before.append(accuracy_score(y_test, y_pred_before))
    precision_list_before.append(precision_score(y_test, y_pred_before, average='weighted'))
    recall_list_before.append(recall_score(y_test, y_pred_before, average='weighted'))
    f1_list_before.append(f1_score(y_test, y_pred_before, average='weighted'))
    confusion_matrices_before.append(confusion_matrix(y_test, y_pred_before))
    
    # Apply SMOTE + Tomek Links to the training data
    smote_tomek = SMOTETomek(random_state=42)
    X_train_smote_tomek, y_train_smote_tomek = smote_tomek.fit_resample(X_train, y_train)
    
    # Initialize and train the SVM model with SMOTE + Tomek Links
    svm_model_smote_tomek = SVC(probability=True, kernel='rbf', random_state=42)
    svm_model_smote_tomek.fit(X_train_smote_tomek, y_train_smote_tomek)
    
    # Predictions and probabilities after SMOTE + Tomek Links
    y_pred_smote_tomek = svm_model_smote_tomek.predict(X_test)
    y_prob_smote_tomek = svm_model_smote_tomek.predict_proba(X_test)
    
    # Calculate entropy after SMOTE + Tomek Links
    entropy_smote_tomek = calculate_entropy(y_prob_smote_tomek)
    entropy_list_smote_tomek.append(entropy_smote_tomek)
    
    # Store metrics after SMOTE + Tomek Links
    accuracy_list_smote_tomek.append(accuracy_score(y_test, y_pred_smote_tomek))
    precision_list_smote_tomek.append(precision_score(y_test, y_pred_smote_tomek))
    recall_list_smote_tomek.append(recall_score(y_test, y_pred_smote_tomek))
    f1_list_smote_tomek.append(f1_score(y_test, y_pred_smote_tomek))
    confusion_matrices_smote_tomek.append(confusion_matrix(y_test, y_pred_smote_tomek))
    
    print(f'Confusion Matrix for Fold {len(confusion_matrices_before)} Before Oversampling:\n', confusion_matrices_before[-1])
    print(f'Confusion Matrix for Fold {len(confusion_matrices_smote_tomek)} After SMOTE + Tomek Links:\n', confusion_matrices_smote_tomek[-1])

# Calculate mean and standard deviation of each metric before oversampling
mean_accuracy_before = np.mean(accuracy_list_before)
std_accuracy_before = np.std(accuracy_list_before)
mean_precision_before = np.mean(precision_list_before)
std_precision_before = np.std(precision_list_before)
mean_recall_before = np.mean(recall_list_before)
std_recall_before = np.std(recall_list_before)
mean_f1_before = np.mean(f1_list_before)
std_f1_before = np.std(f1_list_before)
mean_entropy_before = np.mean(entropy_list_before)
std_entropy_before = np.std(entropy_list_before)

# Calculate mean and standard deviation of each metric after SMOTE + Tomek Links
mean_accuracy_smote_tomek = np.mean(accuracy_list_smote_tomek)
std_accuracy_smote_tomek = np.std(accuracy_list_smote_tomek)
mean_precision_smote_tomek = np.mean(precision_list_smote_tomek)
std_precision_smote_tomek = np.std(precision_list_smote_tomek)
mean_recall_smote_tomek = np.mean(recall_list_smote_tomek)
std_recall_smote_tomek = np.std(recall_list_smote_tomek)
mean_f1_smote_tomek = np.mean(f1_list_smote_tomek)
std_f1_smote_tomek = np.std(f1_list_smote_tomek)
mean_entropy_smote_tomek = np.mean(entropy_list_smote_tomek)
std_entropy_smote_tomek = np.std(entropy_list_smote_tomek)

# Calculate mean confusion matrix before and after SMOTE + Tomek Links
mean_conf_matrix_before = np.mean(confusion_matrices_before, axis=0)
mean_conf_matrix_smote_tomek = np.mean(confusion_matrices_smote_tomek, axis=0)

# Print results before oversampling
print('--- Before Oversampling ---')
print('Mean Accuracy:', mean_accuracy_before)
print('Accuracy Std Dev:', std_accuracy_before)
print('Mean Precision:', mean_precision_before)
print('Precision Std Dev:', std_precision_before)
print('Mean Recall:', mean_recall_before)
print('Recall Std Dev:', std_recall_before)
print('Mean F1-score:', mean_f1_before)
print('F1-score Std Dev:', std_f1_before)
print('Mean Entropy:', mean_entropy_before)
print('Entropy Std Dev:', std_entropy_before)
print('Mean Confusion Matrix:\n', mean_conf_matrix_before)

# Print results after SMOTE + Tomek Links
print('--- After SMOTE + Tomek Links ---')
print('Mean Accuracy:', mean_accuracy_smote_tomek)
print('Accuracy Std Dev:', std_accuracy_smote_tomek)
print('Mean Precision:', mean_precision_smote_tomek)
print('Precision Std Dev:', std_precision_smote_tomek)
print('Mean Recall:', mean_recall_smote_tomek)
print('Recall Std Dev:', std_recall_smote_tomek)
print('Mean F1-score:', mean_f1_smote_tomek)
print('F1-score Std Dev:', std_f1_smote_tomek)
print('Mean Entropy:', mean_entropy_smote_tomek)
print('Entropy Std Dev:', std_entropy_smote_tomek)
print('Mean Confusion Matrix:\n', mean_conf_matrix_smote_tomek)

/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Confusion Matrix for Fold 1 Before Oversampling:
 [[81  0]
 [ 5  0]]
Confusion Matrix for Fold 1 After SMOTE + Tomek Links:
 [[66 15]
 [ 4  1]]


/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Confusion Matrix for Fold 2 Before Oversampling:
 [[81  0]
 [ 5  0]]
Confusion Matrix for Fold 2 After SMOTE + Tomek Links:
 [[67 14]
 [ 4  1]]


/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Confusion Matrix for Fold 3 Before Oversampling:
 [[81  0]
 [ 5  0]]
Confusion Matrix for Fold 3 After SMOTE + Tomek Links:
 [[60 21]
 [ 3  2]]


/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Confusion Matrix for Fold 4 Before Oversampling:
 [[80  0]
 [ 6  0]]
Confusion Matrix for Fold 4 After SMOTE + Tomek Links:
 [[69 11]
 [ 4  2]]


/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Confusion Matrix for Fold 5 Before Oversampling:
 [[80  0]
 [ 6  0]]
Confusion Matrix for Fold 5 After SMOTE + Tomek Links:
 [[63 17]
 [ 1  5]]


/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Confusion Matrix for Fold 6 Before Oversampling:
 [[80  0]
 [ 6  0]]
Confusion Matrix for Fold 6 After SMOTE + Tomek Links:
 [[65 15]
 [ 5  1]]


/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Confusion Matrix for Fold 7 Before Oversampling:
 [[80  0]
 [ 6  0]]
Confusion Matrix for Fold 7 After SMOTE + Tomek Links:
 [[57 23]
 [ 3  3]]


/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Confusion Matrix for Fold 8 Before Oversampling:
 [[80  0]
 [ 6  0]]
Confusion Matrix for Fold 8 After SMOTE + Tomek Links:
 [[62 18]
 [ 3  3]]


/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Confusion Matrix for Fold 9 Before Oversampling:
 [[80  0]
 [ 5  0]]
Confusion Matrix for Fold 9 After SMOTE + Tomek Links:
 [[64 16]
 [ 3  2]]


/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


Confusion Matrix for Fold 10 Before Oversampling:
 [[80  0]
 [ 5  0]]
Confusion Matrix for Fold 10 After SMOTE + Tomek Links:
 [[65 15]
 [ 1  4]]
--- Before Oversampling ---
Mean Accuracy: 0.9359097127222983
Accuracy Std Dev: 0.005682096970161464
Mean Precision: 0.8759592765939133
Precision Std Dev: 0.01063602674427472
Mean Recall: 0.9359097127222983
Recall Std Dev: 0.005682096970161464
Mean F1-score: 0.9049343565899726
F1-score Std Dev: 0.008331939708934689
Mean Entropy: 0.22670256740313155
Entropy Std Dev: 0.00942586759892498
Mean Confusion Matrix:
 [[80.3  0. ]
 [ 5.5  0. ]]
--- After SMOTE + Tomek Links ---
Mean Accuracy: 0.7716142270861833
Accuracy Std Dev: 0.03692568390189449
Mean Precision: 0.12396212546670213
Precision Std Dev: 0.056446973891806494
Mean Recall: 0.4333333333333333
Recall Std Dev: 0.22261077142752
Mean F1-score: 0.1913642100970476
F1-score Std Dev: 0.08905531185704302
Mean Entropy: 0.508063556429099
Entropy Std Dev: 0.029485129750824526
Mean Confusion Matrix:
 [[