In [9]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report 
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix,cohen_kappa_score
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np
import pandas as pd 
import numpy as np
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_score,recall_score,f1_score
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, precision_score, recall_score, f1_score
import numpy as np


from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report 
from sklearn.metrics import confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np
import pandas as pd 
import numpy as np
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_score,recall_score,f1_score
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC



In [10]:
data = pd.read_csv('final_with_covid_AS.csv')
data.head()

CountCases  BedDys  BeddystoCC  Severity  DiedCases  DiedBdDys  Hsptlsns  \
0          17     133    7.823529        75          4          9        13   
1          13     372   28.615385        63          4         34         9   
2           8     106   13.250000        48          4         13         4   
3          45     218    4.844444       153          3         24        42   
4          24     238    9.916667        90          3          8        21   

   April  August  December  ...  Y2013  Y2014  Y2015  Y2016  Y2017  Y2018  \
0      0       0         0  ...      1      0      0      0      0      0   
1      0       0         0  ...      0      0      0      0      0      0   
2      0       0         0  ...      0      0      0      0      0      1   
3      0       0         0  ...      0      0      0      1      0      0   
4      0       1         0  ...      1      0      0      0      0      0   

   Y2019  Y2020  Y2021  CovidPrd  
0      0      0      0         0  
1      0      0      0         0  
2      0      0      0         0  
3      0      0      0         0  
4      0      0      0         0  

[5 rows x 58 columns]

In [11]:
filtered_data5 = data[data['Pedestrian'] == 1]
filtered_data5.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6086 entries, 0 to 54037
Data columns (total 58 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CountCases       6086 non-null   int64  
 1   BedDys           6086 non-null   int64  
 2   BeddystoCC       6086 non-null   float64
 3   Severity         6086 non-null   int64  
 4   DiedCases        6086 non-null   int64  
 5   DiedBdDys        6086 non-null   int64  
 6   Hsptlsns         6086 non-null   int64  
 7   April            6086 non-null   int64  
 8   August           6086 non-null   int64  
 9   December         6086 non-null   int64  
 10  February         6086 non-null   int64  
 11  January          6086 non-null   int64  
 12  July             6086 non-null   int64  
 13  June             6086 non-null   int64  
 14  March            6086 non-null   int64  
 15  May              6086 non-null   int64  
 16  November         6086 non-null   int64  
 17  October          6

In [12]:
num_bins = 2

bed_days_min = filtered_data5['Severity'].min()
bed_days_max = filtered_data5['Severity'].max()

bin_width = (bed_days_max - bed_days_min) / num_bins
bins = [bed_days_min + i * bin_width for i in range(num_bins + 1)]

def bin_function(x):
    for i in range(1, len(bins)):
        if x <= bins[i]:
            return i - 1
    return i

filtered_data5['Bed_days_category'] = filtered_data5['Severity'].apply(bin_function)

/var/folders/3l/xh28kn0j7_7d5hh7fgz188940000gn/T/ipykernel_1964/2563099148.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_data5['Bed_days_category'] = filtered_data5['Severity'].apply(bin_function)


In [13]:
filtered_data5['Bed_days_category'].value_counts()

Bed_days_category
0    5944
1     142
Name: count, dtype: int64

In [14]:
from xgboost import XGBClassifier

X = filtered_data5[['Age1725','Age2639','Age4064','Age6574','Age75plus',
                   
                   'Male','Female',
                   
                   'Regional','MajorCities',

                   'April','December','February','January','July',
                   'June','March','May','November','October','September',

                   'Cntrprt23WldMV','CntrprtFxdStnry','CntrprtHvyVhcl',
                   'CntrprtNClsn','CntrprtOther','CntrprtNMV','CntrprtCrTrkVn',
                   'CntrprtPdlC','CntrprtPdstAnml','CntrprtTrn',

                   'Y2014','Y2015','Y2016','Y2017','Y2018','Y2019','Y2020','Y2021',
                   'Y2013','Y2012',
                   'CovidPrd']]



y = filtered_data5['Bed_days_category']
X_train , X_test , y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)



In [15]:

# Number of folds
n_splits =10

# Initialize StratifiedKFold
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)

# Initialize lists to store metrics for each fold
accuracy_list = []
precision_list = []
recall_list = []
f1_list = []
confusion_matrices = []

# Loop through the StratifiedKFold splits
for train_index, test_index in skf.split(X, y):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    
    xgb_model = XGBClassifier(random_state=42)
    xgb_model.fit(X_train, y_train)
    
    y_pred_xgb = xgb_model.predict(X_test)
    
    accuracy_list.append(accuracy_score(y_test, y_pred_xgb))
    precision_list.append(precision_score(y_test, y_pred_xgb))
    recall_list.append(recall_score(y_test, y_pred_xgb))
    f1_list.append(f1_score(y_test, y_pred_xgb))
    
    conf_matrix = confusion_matrix(y_test, y_pred_xgb)
    confusion_matrices.append(conf_matrix)
    print(f'Confusion Matrix for Fold {len(confusion_matrices)}:\n', conf_matrix)

# Calculate mean and standard deviation of each metric
mean_accuracy = np.mean(accuracy_list)
std_accuracy = np.std(accuracy_list)
mean_precision = np.mean(precision_list)
std_precision = np.std(precision_list)
mean_recall = np.mean(recall_list)
std_recall = np.std(recall_list)
mean_f1 = np.mean(f1_list)
std_f1 = np.std(f1_list)

# Calculate mean confusion matrix
mean_conf_matrix = np.mean(confusion_matrices, axis=0)

print('Mean Accuracy:', mean_accuracy)
print('Accuracy Std Dev:', std_accuracy)
print('Mean Precision:', mean_precision)
print('Precision Std Dev:', std_precision)
print('Mean Recall:', mean_recall)
print('Recall Std Dev:', std_recall)
print('Mean F1-score:', mean_f1)
print('F1-score Std Dev:', std_f1)
print('Mean Confusion Matrix:\n', mean_conf_matrix)
 

Confusion Matrix for Fold 1:
 [[588   6]
 [  9   6]]
Confusion Matrix for Fold 2:
 [[589   5]
 [ 10   5]]
Confusion Matrix for Fold 3:
 [[589   6]
 [  9   5]]
Confusion Matrix for Fold 4:
 [[589   6]
 [ 11   3]]
Confusion Matrix for Fold 5:
 [[591   4]
 [  7   7]]
Confusion Matrix for Fold 6:
 [[590   5]
 [ 10   4]]
Confusion Matrix for Fold 7:
 [[593   1]
 [ 10   4]]
Confusion Matrix for Fold 8:
 [[590   4]
 [ 11   3]]
Confusion Matrix for Fold 9:
 [[590   4]
 [  8   6]]
Confusion Matrix for Fold 10:
 [[589   5]
 [ 12   2]]
Mean Accuracy: 0.9765040294702272
Accuracy Std Dev: 0.003447361594167791
Mean Precision: 0.49829725829725824
Precision Std Dev: 0.14230838676123778
Mean Recall: 0.31619047619047613
Recall Std Dev: 0.10396231656377287
Mean F1-score: 0.3810383204387781
F1-score Std Dev: 0.10651944205297986
Mean Confusion Matrix:
 [[589.8   4.6]
 [  9.7   4.5]]


In [16]:
import pandas as pd

# Initialize a list to store feature importances for each fold
feature_importances = []

# Loop through the StratifiedKFold splits
for train_index, test_index in skf.split(X, y):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    
    xgb_model = XGBClassifier(random_state=42)
    xgb_model.fit(X_train, y_train)
    
    y_pred_xgb = xgb_model.predict(X_test)
    
    # Extract feature importances from the trained model
    feature_importances.append(xgb_model.feature_importances_)

# Convert to a DataFrame for easier manipulation
feature_importances_df = pd.DataFrame(feature_importances, columns=X.columns)

# Calculate the mean importance across all folds
mean_feature_importances = feature_importances_df.mean()

# Sort the feature importances in descending order
sorted_importances = mean_feature_importances.sort_values(ascending=False)

print("Feature Importances:\n", sorted_importances)


Feature Importances:
 Regional           0.301559
CntrprtCrTrkVn     0.249781
CovidPrd           0.048437
Age6574            0.040965
February           0.026994
November           0.021664
Age4064            0.021626
January            0.020928
Y2020              0.018357
September          0.017228
July               0.016208
June               0.015805
Y2021              0.015189
Age1725            0.014864
Y2012              0.014350
Age2639            0.013737
Male               0.013340
December           0.012882
Y2017              0.012295
Y2015              0.011850
May                0.011789
Y2013              0.011359
October            0.011182
Age75plus          0.009541
Y2019              0.009485
April              0.009060
Y2016              0.007742
Y2014              0.007414
Y2018              0.007203
March              0.007168
CntrprtPdlC        0.000000
CntrprtTrn         0.000000
CntrprtPdstAnml    0.000000
Female             0.000000
CntrprtNMV         0.00000

In [17]:
from xgboost import XGBClassifier
from sklearn.metrics import precision_recall_curve, accuracy_score, precision_score, recall_score, confusion_matrix
from sklearn.model_selection import StratifiedKFold
import numpy as np

# Number of folds
n_splits = 10

# Initialize StratifiedKFold
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)

# Initialize lists to store metrics for each fold
accuracy_list = []
precision_list = []
recall_list = []
custom_metric_list = []
confusion_matrices = []

def balance_weighted_f1(precision, recall, beta):
    return (1 + beta**2) * (precision * recall) / (beta**2 * precision + recall)

def find_best_threshold(y_true, y_probs, beta):
    precisions, recalls, thresholds = precision_recall_curve(y_true, y_probs)
    custom_metrics = balance_weighted_f1(precisions, recalls, beta)
    best_index = np.argmax(custom_metrics)
    return thresholds[best_index], custom_metrics[best_index]

# Loop through the StratifiedKFold splits
for train_index, test_index in skf.split(X, y):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    
    # Calculate imbalance ratio and beta
    imbalance_ratio = sum(y_train == 0) / sum(y_train == 1)
    beta = imbalance_ratio / 2
    
    # Initialize XGBoost model
    xgb_model = XGBClassifier(random_state=42, use_label_encoder=False, eval_metric='logloss')
    xgb_model.fit(X_train, y_train)
    
    # Get the predicted probabilities for training set
    y_probs_train = xgb_model.predict_proba(X_train)[:, 1]
    
    # Find the best threshold on the training set using our custom metric
    best_threshold, best_metric = find_best_threshold(y_train, y_probs_train, beta)
    
    # Apply the threshold to the test set
    y_probs_test = xgb_model.predict_proba(X_test)[:, 1]
    y_pred_xgb = (y_probs_test >= best_threshold).astype(int)
    
    # Calculate metrics
    accuracy_list.append(accuracy_score(y_test, y_pred_xgb))
    precision_list.append(precision_score(y_test, y_pred_xgb))
    recall_list.append(recall_score(y_test, y_pred_xgb))
    custom_metric_list.append(best_metric)
    
    # Calculate confusion matrix
    conf_matrix = confusion_matrix(y_test, y_pred_xgb)
    confusion_matrices.append(conf_matrix)
    print(f'Confusion Matrix for Fold {len(confusion_matrices)}:\n', conf_matrix)

# Calculate mean and standard deviation of each metric
mean_accuracy = np.mean(accuracy_list)
std_accuracy = np.std(accuracy_list)
mean_precision = np.mean(precision_list)
std_precision = np.std(precision_list)
mean_recall = np.mean(recall_list)
std_recall = np.std(recall_list)
mean_custom_metric = np.mean(custom_metric_list)
std_custom_metric = np.std(custom_metric_list)

# Calculate mean confusion matrix
mean_conf_matrix = np.mean(confusion_matrices, axis=0).astype(int)

print('Mean Accuracy:', mean_accuracy)
print('Accuracy Std Dev:', std_accuracy)
print('Mean Precision:', mean_precision)
print('Precision Std Dev:', std_precision)
print('Mean Recall:', mean_recall)
print('Recall Std Dev:', std_recall)
print('Mean Custom Metric (Balance-Weighted F1):', mean_custom_metric)
print('Custom Metric Std Dev:', std_custom_metric)
print('Mean Confusion Matrix:\n', mean_conf_matrix)


Confusion Matrix for Fold 1:
 [[557  37]
 [  2  13]]
Confusion Matrix for Fold 2:
 [[570  24]
 [  5  10]]
Confusion Matrix for Fold 3:
 [[561  34]
 [  2  12]]
Confusion Matrix for Fold 4:
 [[553  42]
 [  1  13]]
Confusion Matrix for Fold 5:
 [[553  42]
 [  2  12]]
Confusion Matrix for Fold 6:
 [[564  31]
 [  3  11]]
Confusion Matrix for Fold 7:
 [[580  14]
 [  4  10]]
Confusion Matrix for Fold 8:
 [[572  22]
 [  1  13]]
Confusion Matrix for Fold 9:
 [[560  34]
 [  2  12]]
Confusion Matrix for Fold 10:
 [[563  31]
 [  2  12]]
Mean Accuracy: 0.9449620819289603
Accuracy Std Dev: 0.012856577582967758
Mean Precision: 0.28635124035213255
Precision Std Dev: 0.057909878907006204
Mean Recall: 0.8319047619047618
Recall Std Dev: 0.08106574695146025
Mean Custom Metric (Balance-Weighted F1): 0.9953975353915375
Custom Metric Std Dev: 0.0007902729223017033
Mean Confusion Matrix:
 [[563  31]
 [  2  11]]


In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import precision_recall_curve, accuracy_score, precision_score, recall_score, confusion_matrix
from sklearn.model_selection import StratifiedKFold
import numpy as np

# Number of folds
n_splits = 10

# Initialize StratifiedKFold
skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=42)

# Initialize lists to store metrics for each fold
accuracy_list = []
precision_list = []
recall_list = []
custom_metric_list = []
confusion_matrices = []

def balance_weighted_f1(precision, recall, beta):
    return (1 + beta**2) * (precision * recall) / (beta**2 * precision + recall)

def find_best_threshold(y_true, y_probs, beta):
    precisions, recalls, thresholds = precision_recall_curve(y_true, y_probs)
    custom_metrics = balance_weighted_f1(precisions, recalls, beta)
    best_index = np.argmax(custom_metrics)
    return thresholds[best_index], custom_metrics[best_index]

# Loop through the StratifiedKFold splits
for train_index, test_index in skf.split(X, y):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    
    # Calculate imbalance ratio and beta
    imbalance_ratio = sum(y_train == 0) / sum(y_train == 1)
    beta = imbalance_ratio / 2
    
    # Initialize Logistic Regression model
    lr_model = LogisticRegression(random_state=42)
    lr_model.fit(X_train, y_train)
    
    # Get the predicted probabilities for training set
    y_probs_train = lr_model.predict_proba(X_train)[:, 1]
    
    # Find the best threshold on the training set using our custom metric
    best_threshold, best_metric = find_best_threshold(y_train, y_probs_train, beta)
    
    # Apply the threshold to the test set
    y_probs_test = lr_model.predict_proba(X_test)[:, 1]
    y_pred_lr = (y_probs_test >= best_threshold).astype(int)
    
    # Calculate metrics
    accuracy_list.append(accuracy_score(y_test, y_pred_lr))
    precision_list.append(precision_score(y_test, y_pred_lr))
    recall_list.append(recall_score(y_test, y_pred_lr))
    custom_metric_list.append(best_metric)
    
    # Calculate confusion matrix
    conf_matrix = confusion_matrix(y_test, y_pred_lr)
    confusion_matrices.append(conf_matrix)
    print(f'Confusion Matrix for Fold {len(confusion_matrices)}:\n', conf_matrix)

# Calculate mean and standard deviation of each metric
mean_accuracy = np.mean(accuracy_list)
std_accuracy = np.std(accuracy_list)
mean_precision = np.mean(precision_list)
std_precision = np.std(precision_list)
mean_recall = np.mean(recall_list)
std_recall = np.std(recall_list)
mean_custom_metric = np.mean(custom_metric_list)
std_custom_metric = np.std(custom_metric_list)

# Calculate mean confusion matrix
mean_conf_matrix = np.mean(confusion_matrices, axis=0).astype(int)

print('Mean Accuracy:', mean_accuracy)
print('Accuracy Std Dev:', std_accuracy)
print('Mean Precision:', mean_precision)
print('Precision Std Dev:', std_precision)
print('Mean Recall:', mean_recall)
print('Recall Std Dev:', std_recall)
print('Mean Custom Metric (Balance-Weighted F1):', mean_custom_metric)
print('Custom Metric Std Dev:', std_custom_metric)
print('Mean Confusion Matrix:\n', mean_conf_matrix)


/var/folders/3l/xh28kn0j7_7d5hh7fgz188940000gn/T/ipykernel_1915/3032758396.py:20: RuntimeWarning: invalid value encountered in divide
  return (1 + beta**2) * (precision * recall) / (beta**2 * precision + recall)
/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Confusion Matrix for Fold 1:
 [[594   0]
 [ 15   0]]
Confusion Matrix for Fold 2:
 [[512  82]
 [  1  14]]
Confusion Matrix for Fold 3:
 [[500  95]
 [  0  14]]
Confusion Matrix for Fold 4:
 [[508  87]
 [  0  14]]
Confusion Matrix for Fold 5:
 [[461 134]
 [  0  14]]
Confusion Matrix for Fold 6:
 [[510  85]
 [  1  13]]
Confusion Matrix for Fold 7:
 [[515  79]
 [  0  14]]
Confusion Matrix for Fold 8:
 [[594   0]
 [ 14   0]]
Confusion Matrix for Fold 9:
 [[514  80]
 [  0  14]]
Confusion Matrix for Fold 10:
 [[503  91]
 [  0  14]]
Mean Accuracy: 0.8744771411286838
Accuracy Std Dev: 0.056433410988173116
Mean Precision: 0.1072942355465735
Precision Std Dev: 0.05569907868159139
Mean Recall: 0.7861904761904762
Recall Std Dev: 0.3940052487650663
Mean Custom Metric (Balance-Weighted F1): nan
Custom Metric Std Dev: nan
Mean Confusion Matrix:
 [[521  73]
 [  3  11]]


/var/folders/3l/xh28kn0j7_7d5hh7fgz188940000gn/T/ipykernel_1915/3032758396.py:20: RuntimeWarning: invalid value encountered in divide
  return (1 + beta**2) * (precision * recall) / (beta**2 * precision + recall)
/Users/amin/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
